#pragma once

#define BLOCK_VTABLE_IS_REDSTONE_PROVIDER 18
#define BLOCK_VTABLE_IS_SIGNAL_SOURCE 20
#define BLOCK_VTABLE_GET_DIRECT_SIGNAL 21
#define BLOCK_VTABLE_ON_PLACE 27
#define BLOCK_VTABLE_ON_REDSTONE_UPDATE 32
#define BLOCK_VTABLE_NEIGHBOR_CHANGED 46
#define BLOCK_VTABLE_PLAYER_DESTROY 61
